name: "pull request title validator"
description: "Checks whether a pull request title adheres to the conventional commit specification"
author: "Levi van Noort"

branding:
  icon: 'git-pull-request'
  color: 'green'

runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  types:
    description: 'Comma-separated list of valid commit types'
    required: false
    default: 'fix,feat,chore,docs,build,ci,refactor,perf,test'
  scopes:
    description: 'Comma-separated list of valid scopes'
    required: false
    default: ''
