name: continuous-integration

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: checkout code
        uses: actions/checkout@v4

      - name: run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

  test:
    runs-on: ubuntu-latest
    steps:
      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: checkout code
        uses: actions/checkout@v4
      
      - name: pull request title validator
        uses: ./ # kontrolplane/pull-request-title-validation@latest
