name: continuous-integration

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: checkout code
        uses: actions/checkout@v4
      
      - name: pull request title validator
        uses: ./ # kontrolplane/pull-request-title-validator@latest
        with:
          types: "fix,chore"