name: publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: fetch tags
        run: git fetch --force --tags

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: publish package
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}